fix(types): NgxKeyValuePair is actually an array
nginx/njs pull request #768
Opened 2024-07-30 12:23 UTC by TPXP

### Proposed changes

Correct the type definition for `NgxSharedDict.items()`. At runtime, I found out it returns an array of `[key, value]` objects, just like `Object.items()`. As documented here https://nginx.org/en/docs/njs/reference.html#dict_items

### Checklist

Before creating a PR, run through this checklist and mark each as complete:
- [ ] I have read the [`CONTRIBUTING`](CONTRIBUTING.md) document
- [x] If applicable, I have added tests that prove my fix is effective or that my feature works
- [x] If applicable, I have checked that any relevant tests pass after adding my changes

## Minimal reproduction
```
function dumpItems(r) {
  ngx.shared.myarray.set("hello", "world")
  console.log(ngx.shared.myarray.items()[0])
}
```
Console output
```
2024/07/30 12:14:42 [info] 22#22: *1 js: ['hello','world']
```

2024-08-07 22:10 UTC, xeioex requested changes
We have our own commit log rules. The best way to get it is to `grep` commit history.

Proposed commit log:
```
Types: fixed NgxKeyValuePair definition.

NgxSharedDict.items() returns an array of `[key, value]` pairs, as `Object.entries()`.
```

2024-08-07 22:11 UTC, xeioex commented on ts/ngx_core.d.ts
> +type NgxKeyValuePair<V> = [key: string, value: V];
Also, it seems here we can remove names `key` and `value`.

To `type NgxKeyValuePair<V> = [string, V];`

2024-08-14 09:59 UTC, TPXP commented
Thanks for your feedback, I've reworded the commit and updated the type definition since adding names to array entries doesn't change much indeed (I hoped it would give some hints in IDEs but that does not seem to be the case).

2024-08-14 22:18 UTC, xeioex approved these changes

2024-08-14 22:19 UTC, merged