Atomic keys introduction for strings, symbols, small numbers.
nginx/njs pull request #777
Opened 2024-08-30 01:48 UTC by VadimZhestikov

### Proposed changes

This is series of commits which introduce internal atomic representation for
strings, symbols and small numbers as keys for access object properties.

These commits are intended to speed up access to object properties. 

Step 1:
    Remove long strings from njs core to simplify code and make it more regular.
    Reserve atom_id field in njs_value_t.

Notes:
    a)  Each commit is fully and successfully tested for regressions with all local tests;
    b) This PR is draft for internal review, I'll extend it by additional commits as
        they will be merged here from my hg sandbox.
    c) As soon as last commit will be added/reviewed, draft status from this PR can be removed,
        and PR applied then.

### Checklist

Before creating a PR, run through this checklist and mark each as complete:
- [X] I have read the [`CONTRIBUTING`](CONTRIBUTING.md) document
- [ ] If applicable, I have added tests that prove my fix is effective or that my feature works
- [X] If applicable, I have checked that any relevant tests pass after adding my changes

2024-09-04 06:08 UTC, xeioex reviewed
See njs_object_iterate() and `This cannot fail` comment.
This is not true anymore and should be checked for error as well.

2024-09-04 06:08 UTC, xeioex commented on src/njs_builtin.c
> +    } else {
Style: else block can be removed.

2024-09-04 06:08 UTC, xeioex commented on src/njs_builtin.c
> +//    ret = njs_string_new(vm, &prop->name, buf, p - buf, 0);
Extra line. Empty line is needed.

2024-09-04 06:11 UTC, xeioex requested changes
Suggested commit log:

`Removed built-in short string.`

2024-09-04 20:23 UTC, VadimZhestikov commented on src/njs_promise.c
> +static const njs_value_t  string_constructor = njs_string("constructor");
They will have unique names at next steps, to guarantee use of single value for same strings.

2024-09-04 23:44 UTC, xeioex requested changes

2024-09-04 23:44 UTC, xeioex commented on src/njs_object.c
> +                                     p - start);
Style: ' p - start' should start just after "(" on the line below.

2024-09-04 23:44 UTC, xeioex commented on src/njs_object.c
> +static const njs_value_t  constructor_string = njs_string("constructor");
We already have `njs_string_ctor` declared globally in the patch for this.

2024-09-04 23:44 UTC, xeioex commented on src/njs_function.c
> +static const njs_value_t  proto_string = njs_string("prototype");
We already have `njs_string_prototype` declared globally in the patch.

2024-09-04 23:44 UTC, xeioex commented on src/njs_object.c
> +static const njs_value_t  proto_string = njs_string("prototype");
We already have `njs_string_prototype` declared globally in the patch.

2024-09-05 00:58 UTC, VadimZhestikov commented
I'll squash 'Macro NJS_DECLARE_PROP_HANDLER is used for Uint8ClampedArray.' later.

2024-09-17 19:16 UTC, closed without merging